# Generated by Django 4.2.16 on 2024-10-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0002_burger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Molong',
        ),
    ]
